SELECT REDS.REGISTER_EVENT_ID, REDS.PLANNED_START_DATE, REDS.PLANNED_END_DATE, ERER.DESCRIPTION, ERER.ROOM_CODE, ERER.WEEK_PATTERN_TEXT_MATCH, ERER.SESSION_START_DATE
            FROM ebslive.dbo.REGISTER_EVENT_DETAILS_SLOTS AS REDS
            LEFT JOIN ebslive.dbo.sessions AS SE ON SE.session_code = REDS.session_code
            INNER JOIN ebslive.dbo.EBS_REG_EVENTS_ROOM AS ERER
            ON REDS.REGISTER_EVENT_ID = ERER.REGISTER_EVENT_ID
            WHERE REDS.OBJECT_ID = ?
            AND REDS.SESSION_CODE = ?